# Generated by Django 6.0.3 on 2026-03-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='state_location',
            new_name='business_name',
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
