# Generated by Django 6.0.3 on 2026-03-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_state_location_user_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TESTER', 'Tester')], default='ADMIN', max_length=20),
        ),
    ]
