# Generated by Django 6.0.3 on 2026-03-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], db_index=True, default='facebook', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.URLField(blank=True, max_length=500, null=True)),
                ('current_state', models.CharField(default='ENTRY', max_length=100)),
                ('bot_attributes', models.JSONField(blank=True, default=dict)),
                ('score', models.IntegerField(default=0, help_text='Latest progress_score from bot (0–100)')),
                ('status', models.CharField(choices=[('coldLead', 'Cold Lead'), ('nurture', 'Nurture'), ('warmLead', 'Warm Lead'), ('hotLead', 'Hot Lead')], db_index=True, default='coldLead', help_text='Auto-derived: coldLead<60, nurture=60-70, warmLead=70-80, hotLead≥80', max_length=20)),
                ('last_interaction', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Sender',
                'verbose_name_plural': 'Senders',
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_from_bot', models.BooleanField(db_index=True, default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversation.platformuser')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sender', 'timestamp'], name='conversatio_sender__8e6cf0_idx')],
            },
        ),
    ]
